version: "3.8"

services: 
  mysql:
    image: mysql:5.7
    ports: 
      - 3306:3306
    env_file: 
      - ./env/mysql.env
    volumes: 
      - ./data:/var/lib/mysql
    networks:
      - mysql_network
      
networks:
  mysql_network:
    driver: bridge
    
